///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.Admin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Assigned_SYSTEM_APPROVER recording.
    /// </summary>
    [TestModule("98c8b5b7-a2c5-4343-b938-74ee4c792288", ModuleType.Recording, 1)]
    public partial class Assigned_SYSTEM_APPROVER : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Assigned_SYSTEM_APPROVER instance = new Assigned_SYSTEM_APPROVER();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Assigned_SYSTEM_APPROVER()
        {
            varCondition_Type = "";
            varSYS_APPROVAL = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Assigned_SYSTEM_APPROVER Instance
        {
            get { return instance; }
        }

#region Variables

        string _varCondition_Type;

        /// <summary>
        /// Gets or sets the value of variable varCondition_Type.
        /// </summary>
        [TestVariable("6f955bbe-70b4-4784-a0d4-6453fdb6d853")]
        public string varCondition_Type
        {
            get { return _varCondition_Type; }
            set { _varCondition_Type = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varSYS_APPROVAL.
        /// </summary>
        [TestVariable("5206f5d4-e243-4eb8-aacc-bb8fdb335d0e")]
        public string varSYS_APPROVAL
        {
            get { return repo.varSYS_APPROVAL; }
            set { repo.varSYS_APPROVAL = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SimpleMDG_Admin.Workflow_Settings.mn_Workflow_Settings'", repo.SimpleMDG_Admin.Workflow_Settings.mn_Workflow_SettingsInfo, new ActionTimeout(30000), new RecordItemIndex(0));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Workflow_SettingsInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.mn_Workflow_Settings' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.mn_Workflow_SettingsInfo, new RecordItemIndex(1));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Workflow_Settings.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(2));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.mn_Condition_Settings' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.mn_Condition_SettingsInfo, new RecordItemIndex(3));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Condition_Settings.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_Type'", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_TypeInfo, new ActionTimeout(30000), new RecordItemIndex(5));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_TypeInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_Type'", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_TypeInfo, new RecordItemIndex(6));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_TypeInfo.WaitForAttributeEqual(5000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_Type'.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_TypeInfo, new RecordItemIndex(7));
            Keyboard.PrepareFocus(repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_Type);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(8));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'TRUONG1' with focus on 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_Type'.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_TypeInfo, new RecordItemIndex(9));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_Type.PressKeys("TRUONG1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(10));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Search_Condition_Type_Action' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Search_Condition_Type_ActionInfo, new RecordItemIndex(11));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Search_Condition_Type_Action.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(12));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Edit_Condition_Table' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Edit_Condition_TableInfo, new RecordItemIndex(13));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Edit_Condition_Table.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Choose_Approver' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Choose_ApproverInfo, new RecordItemIndex(14));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Choose_Approver.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Select_Members' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Select_MembersInfo, new RecordItemIndex(15));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Select_Members.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'SYSTEM_APPROVER' with focus on 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Select_Members'.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Select_MembersInfo, new RecordItemIndex(16));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Select_Members.PressKeys("SYSTEM_APPROVER");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Search_Select_Members_Action' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Search_Select_Members_ActionInfo, new RecordItemIndex(17));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Search_Select_Members_Action.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.lb_Select_Members_SYS_APPROVAL' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.lb_Select_Members_SYS_APPROVALInfo, new RecordItemIndex(18));
            repo.SimpleMDG_Admin.Workflow_Settings.lb_Select_Members_SYS_APPROVAL.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Update_Confition_Table' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Update_Confition_TableInfo, new RecordItemIndex(19));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Update_Confition_Table.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(20));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Back_Admin' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Back_AdminInfo, new RecordItemIndex(21));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Back_Admin.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(22));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.mn_Template_Setting' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.mn_Template_SettingInfo, new RecordItemIndex(23));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Template_Setting.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
