///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.Admin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Assigned_Admin recording.
    /// </summary>
    [TestModule("285ebdc0-8444-4c79-ae60-892eff99440c", ModuleType.Recording, 1)]
    public partial class Assigned_Admin : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Assigned_Admin instance = new Assigned_Admin();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Assigned_Admin()
        {
            varCondition_Type = "";
            varSYS_APPROVAL = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Assigned_Admin Instance
        {
            get { return instance; }
        }

#region Variables

        string _varCondition_Type;

        /// <summary>
        /// Gets or sets the value of variable varCondition_Type.
        /// </summary>
        [TestVariable("5d6e930e-1efb-4498-95fe-d149417a0c0e")]
        public string varCondition_Type
        {
            get { return _varCondition_Type; }
            set { _varCondition_Type = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varSYS_APPROVAL.
        /// </summary>
        [TestVariable("895f5c8f-517e-49a0-8cfc-43daabeeabdd")]
        public string varSYS_APPROVAL
        {
            get { return repo.varSYS_APPROVAL; }
            set { repo.varSYS_APPROVAL = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.mn_Workflow_Settings' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.mn_Workflow_SettingsInfo, new RecordItemIndex(0));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Workflow_Settings.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(1));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.mn_Condition_Settings' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.mn_Condition_SettingsInfo, new RecordItemIndex(2));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Condition_Settings.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_Type' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_TypeInfo, new RecordItemIndex(3));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_Type.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_Type'.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_TypeInfo, new RecordItemIndex(5));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_Type.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varCondition_Type' with focus on 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_Type'.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_TypeInfo, new RecordItemIndex(7));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Condition_Type.PressKeys(varCondition_Type);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(8));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Search_Condition_Type_Action' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Search_Condition_Type_ActionInfo, new RecordItemIndex(9));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Search_Condition_Type_Action.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(10));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Edit_Condition_Table' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Edit_Condition_TableInfo, new RecordItemIndex(11));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Edit_Condition_Table.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Choose_Approver' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Choose_ApproverInfo, new RecordItemIndex(12));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Choose_Approver.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Select_Members' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Select_MembersInfo, new RecordItemIndex(13));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Select_Members.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varSYS_APPROVAL' with focus on 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Select_Members'.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Select_MembersInfo, new RecordItemIndex(14));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Select_Members.PressKeys(varSYS_APPROVAL);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Search_Select_Members_Action' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Search_Select_Members_ActionInfo, new RecordItemIndex(15));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Search_Select_Members_Action.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.lb_Select_Members_Admin' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.lb_Select_Members_AdminInfo, new RecordItemIndex(16));
            repo.SimpleMDG_Admin.Workflow_Settings.lb_Select_Members_Admin.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Update_Confition_Table' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Update_Confition_TableInfo, new RecordItemIndex(17));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Update_Confition_Table.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(18));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Back_Admin' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Back_AdminInfo, new RecordItemIndex(19));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Back_Admin.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(20));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.mn_Template_Setting' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.mn_Template_SettingInfo, new RecordItemIndex(21));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Template_Setting.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
