///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EDF__PRD_MM01.Admin
{
    public partial class By_Pass_Stewards_ON
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

       
        public void Set_To_True_ByPass(RepoItemInfo inputtagInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bypass Steward Review.", inputtagInfo);
            //inputtagInfo.FindAdapter<InputTag>().Click();
            Report.Log(ReportLevel.Info, "Bypass Steward", inputtagInfo.FindAdapter<InputTag>().Checked.ToString(), inputtagInfo);
            Report.Info(inputtagInfo.FindAdapter<InputTag>().Checked.ToString());
            var chk_Bypass_Steward_Check = repo.SimpleMDG_Admin.chk_Bypass_Steward_Check;

            if(inputtagInfo.FindAdapter<InputTag>().Checked == "False")
            {
            	chk_Bypass_Steward_Check.Click();
            	//inputtagInfo.FindAdapter<InputTag>().Click();
            	
            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.btn_Save_Config' at Center.", repo.SimpleMDG_Admin.btn_Save_ConfigInfo, new RecordItemIndex(7));
            	repo.SimpleMDG_Admin.btn_Save_Config.Click();
           	 	Delay.Milliseconds(0);
            
	            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(8));
	            Delay.Duration(2000, false);
            
	            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.btn_Active_Config' at Center.", repo.SimpleMDG_Admin.btn_Active_ConfigInfo, new RecordItemIndex(9));
	            repo.SimpleMDG_Admin.btn_Active_Config.Click();
	            Delay.Milliseconds(0);
            }
        }

       
    }
}
