///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.Admin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Workflow_Settings_Multiple_Approvers recording.
    /// </summary>
    [TestModule("33653f88-b740-4f0f-baf7-0af7d6e88005", ModuleType.Recording, 1)]
    public partial class Workflow_Settings_Multiple_Approvers : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Workflow_Settings_Multiple_Approvers instance = new Workflow_Settings_Multiple_Approvers();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Workflow_Settings_Multiple_Approvers()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Workflow_Settings_Multiple_Approvers Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(0));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.mn_Workflow_Settings' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.mn_Workflow_SettingsInfo, new RecordItemIndex(1));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Workflow_Settings.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(2));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.mn_Approval_Process' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.mn_Approval_ProcessInfo, new RecordItemIndex(3));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Approval_Process.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(4));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'SimpleMDG_Admin.Workflow_Settings.btn_Add_New_Section'", repo.SimpleMDG_Admin.Workflow_Settings.btn_Add_New_SectionInfo, new ActionTimeout(5000), new RecordItemIndex(5));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Add_New_SectionInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Add_New_Section' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Add_New_SectionInfo, new RecordItemIndex(6));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Add_New_Section.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Add_New_Section' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Add_New_SectionInfo, new RecordItemIndex(8));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Add_New_Section.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Section' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_SectionInfo, new RecordItemIndex(9));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Section.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'PRODUCTDESCRIPTION' with focus on 'SimpleMDG_Admin.Workflow_Settings.txt_Search_Section'.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_SectionInfo, new RecordItemIndex(10));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Search_Section.PressKeys("PRODUCTDESCRIPTION");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.lb_Select_Section' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.lb_Select_SectionInfo, new RecordItemIndex(11));
            repo.SimpleMDG_Admin.Workflow_Settings.lb_Select_Section.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'SimpleMDG_Admin.Workflow_Settings.txt_Section_Order'.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Section_OrderInfo, new RecordItemIndex(12));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Section_Order.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Create_Section_Order' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Create_Section_OrderInfo, new RecordItemIndex(13));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Create_Section_Order.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(14));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.lb_Select_Section_Line' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.lb_Select_Section_LineInfo, new RecordItemIndex(15));
            repo.SimpleMDG_Admin.Workflow_Settings.lb_Select_Section_Line.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(16));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Add_Approve_Sequences' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Add_Approve_SequencesInfo, new RecordItemIndex(17));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Add_Approve_Sequences.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(18));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '10' with focus on 'SimpleMDG_Admin.Workflow_Settings.txt_Approval_Level'.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Approval_LevelInfo, new RecordItemIndex(19));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Approval_Level.PressKeys("10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'TRUONG3' with focus on 'SimpleMDG_Admin.Workflow_Settings.txt_Access_Sequences'.", repo.SimpleMDG_Admin.Workflow_Settings.txt_Access_SequencesInfo, new RecordItemIndex(20));
            repo.SimpleMDG_Admin.Workflow_Settings.txt_Access_Sequences.PressKeys("TRUONG3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(21));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.lb_Select_Access_Sequences' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.lb_Select_Access_SequencesInfo, new RecordItemIndex(22));
            repo.SimpleMDG_Admin.Workflow_Settings.lb_Select_Access_Sequences.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(23));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_CReate_Access_Sequences' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_CReate_Access_SequencesInfo, new RecordItemIndex(24));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_CReate_Access_Sequences.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(25));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Save_Current_Change' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Save_Current_ChangeInfo, new RecordItemIndex(26));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Save_Current_Change.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(27));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Back_Admin' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Back_AdminInfo, new RecordItemIndex(28));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Back_Admin.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.mn_Template_Setting' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.mn_Template_SettingInfo, new RecordItemIndex(29));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Template_Setting.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
