///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.Admin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Workflow_Settings_Single_Approver recording.
    /// </summary>
    [TestModule("782506ee-70c4-4e2c-a867-d6d15bf2edda", ModuleType.Recording, 1)]
    public partial class Workflow_Settings_Single_Approver : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Workflow_Settings_Single_Approver instance = new Workflow_Settings_Single_Approver();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Workflow_Settings_Single_Approver()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Workflow_Settings_Single_Approver Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(0));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.mn_Workflow_Settings' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.mn_Workflow_SettingsInfo, new RecordItemIndex(1));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Workflow_Settings.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(2));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.mn_Approval_Process' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.mn_Approval_ProcessInfo, new RecordItemIndex(3));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Approval_Process.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(4));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'SimpleMDG_Admin.Workflow_Settings.btn_Delete_Section_Order'", repo.SimpleMDG_Admin.Workflow_Settings.btn_Delete_Section_OrderInfo, new RecordItemIndex(5));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Delete_Section_OrderInfo.WaitForAttributeEqual(5000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Delete_Section_Order' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Delete_Section_OrderInfo, new RecordItemIndex(6));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Delete_Section_Order.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'SimpleMDG_Admin.Workflow_Settings.btn_Save_Current_Change'", repo.SimpleMDG_Admin.Workflow_Settings.btn_Save_Current_ChangeInfo, new RecordItemIndex(8));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Save_Current_ChangeInfo.WaitForAttributeEqual(5000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Save_Current_Change' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Save_Current_ChangeInfo, new RecordItemIndex(9));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Save_Current_Change.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(10));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'SimpleMDG_Admin.Workflow_Settings.btn_Back_Admin'", repo.SimpleMDG_Admin.Workflow_Settings.btn_Back_AdminInfo, new RecordItemIndex(11));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Back_AdminInfo.WaitForAttributeEqual(5000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.btn_Back_Admin' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.btn_Back_AdminInfo, new RecordItemIndex(12));
            repo.SimpleMDG_Admin.Workflow_Settings.btn_Back_Admin.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(13));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG_Admin.Workflow_Settings.mn_Template_Setting' at Center.", repo.SimpleMDG_Admin.Workflow_Settings.mn_Template_SettingInfo, new RecordItemIndex(14));
            repo.SimpleMDG_Admin.Workflow_Settings.mn_Template_Setting.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
