///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Input_Product recording.
    /// </summary>
    [TestModule("b2ba5356-5c8c-4cba-8be8-d64cc320a809", ModuleType.Recording, 1)]
    public partial class Input_Product : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EDF__PRD_MM01Repository repository.
        /// </summary>
        public static EDF__PRD_MM01Repository repo = EDF__PRD_MM01Repository.Instance;

        static Input_Product instance = new Input_Product();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Input_Product()
        {
            varMaterial_Number = "";
            varMaterial_description = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Input_Product Instance
        {
            get { return instance; }
        }

#region Variables

        string _varMaterial_Number;

        /// <summary>
        /// Gets or sets the value of variable varMaterial_Number.
        /// </summary>
        [TestVariable("65816b0a-c999-4fe7-961b-37e7e37223c9")]
        public string varMaterial_Number
        {
            get { return _varMaterial_Number; }
            set { _varMaterial_Number = value; }
        }

        string _varMaterial_description;

        /// <summary>
        /// Gets or sets the value of variable varMaterial_description.
        /// </summary>
        [TestVariable("5454f0c0-0087-40d2-ace4-48f28e470a67")]
        public string varMaterial_description
        {
            get { return _varMaterial_description; }
            set { _varMaterial_description = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Input_Data.Product_Info.txt_Material_Number' at Center.", repo.ApplicationUnderTest.Input_Data.Product_Info.txt_Material_NumberInfo, new RecordItemIndex(0));
            //repo.ApplicationUnderTest.Input_Data.Product_Info.txt_Material_Number.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varMaterial_Number' with focus on 'ApplicationUnderTest.Input_Data.Product_Info.txt_Material_Number'.", repo.ApplicationUnderTest.Input_Data.Product_Info.txt_Material_NumberInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Input_Data.Product_Info.txt_Material_Number.PressKeys(varMaterial_Number);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Input_Data.Product_Info.btn_Add_Lang' at Center.", repo.ApplicationUnderTest.Input_Data.Product_Info.btn_Add_LangInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Input_Data.Product_Info.btn_Add_Lang.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Input_Data.Product_Info.txt_Material_description' at Center.", repo.ApplicationUnderTest.Input_Data.Product_Info.txt_Material_descriptionInfo, new RecordItemIndex(3));
            //repo.ApplicationUnderTest.Input_Data.Product_Info.txt_Material_description.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varMaterial_description' with focus on 'ApplicationUnderTest.Input_Data.Product_Info.txt_Material_description'.", repo.ApplicationUnderTest.Input_Data.Product_Info.txt_Material_descriptionInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Input_Data.Product_Info.txt_Material_description.PressKeys(varMaterial_description);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Input_Data.Product_Info.btn_Add_New_description' at Center.", repo.ApplicationUnderTest.Input_Data.Product_Info.btn_Add_New_descriptionInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Input_Data.Product_Info.btn_Add_New_description.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
