///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LogOut recording.
    /// </summary>
    [TestModule("33e22859-0dc9-472a-b142-00af133a69fa", ModuleType.Recording, 1)]
    public partial class LogOut : ITestModule
    {
        /// <summary>
        /// Holds an instance of the S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static S2022_PRD_MM01_NON_DUPRepository repo = S2022_PRD_MM01_NON_DUPRepository.Instance;

        static LogOut instance = new LogOut();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LogOut()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LogOut Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.LogOut.btn_Select_Profile' at Center.", repo.SimpleMDG.LogOut.btn_Select_ProfileInfo, new RecordItemIndex(0));
            repo.SimpleMDG.LogOut.btn_Select_Profile.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.LogOut.mn_Log_Out' at Center.", repo.SimpleMDG.LogOut.mn_Log_OutInfo, new RecordItemIndex(1));
            repo.SimpleMDG.LogOut.mn_Log_Out.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(2));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.LogOut.btn_Confirm_Logout' at Center.", repo.SimpleMDG.LogOut.btn_Confirm_LogoutInfo, new RecordItemIndex(3));
            repo.SimpleMDG.LogOut.btn_Confirm_Logout.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(4));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'SimpleMDG.LogOut.link_LogOut_Confirm'", repo.SimpleMDG.LogOut.link_LogOut_ConfirmInfo, new ActionTimeout(10000), new RecordItemIndex(5));
            repo.SimpleMDG.LogOut.link_LogOut_ConfirmInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.LogOut.link_LogOut_Confirm' at Center.", repo.SimpleMDG.LogOut.link_LogOut_ConfirmInfo, new RecordItemIndex(6));
            repo.SimpleMDG.LogOut.link_LogOut_Confirm.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(7));
            Delay.Duration(5000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
