///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.SPMG_Action
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CopyCRFromExits recording.
    /// </summary>
    [TestModule("73cb5b78-2756-486a-8c5d-1f266f628bf8", ModuleType.Recording, 1)]
    public partial class CopyCRFromExits : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static CopyCRFromExits instance = new CopyCRFromExits();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CopyCRFromExits()
        {
            varCRNumber = "";
            varMaterial_Number = "";
            varMaterial_description = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CopyCRFromExits Instance
        {
            get { return instance; }
        }

#region Variables

        string _varMaterial_description;

        /// <summary>
        /// Gets or sets the value of variable varMaterial_description.
        /// </summary>
        [TestVariable("cd305560-f25a-4537-8f2e-eb42d4e26897")]
        public string varMaterial_description
        {
            get { return _varMaterial_description; }
            set { _varMaterial_description = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varCRNumber.
        /// </summary>
        [TestVariable("586d863a-e028-47af-9e69-64b7a175b183")]
        public string varCRNumber
        {
            get { return repo.varCRNumber; }
            set { repo.varCRNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varMaterial_Number.
        /// </summary>
        [TestVariable("dc898e14-7c6e-4058-aea5-7a354d0eb01a")]
        public string varMaterial_Number
        {
            get { return repo.varMaterial_Number; }
            set { repo.varMaterial_Number = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 20s to exist. Associated repository item: 'SimpleMDG.Copy_CR.txt_Search_CR'", repo.SimpleMDG.Copy_CR.txt_Search_CRInfo, new ActionTimeout(20000), new RecordItemIndex(0));
            repo.SimpleMDG.Copy_CR.txt_Search_CRInfo.WaitForExists(20000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Copy_CR.txt_Search_CR' at Center.", repo.SimpleMDG.Copy_CR.txt_Search_CRInfo, new RecordItemIndex(1));
            repo.SimpleMDG.Copy_CR.txt_Search_CR.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SimpleMDG.Copy_CR.txt_Search_CR'.", repo.SimpleMDG.Copy_CR.txt_Search_CRInfo, new RecordItemIndex(3));
            repo.SimpleMDG.Copy_CR.txt_Search_CR.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varCRNumber' with focus on 'SimpleMDG.Copy_CR.txt_Search_CR'.", repo.SimpleMDG.Copy_CR.txt_Search_CRInfo, new RecordItemIndex(5));
            repo.SimpleMDG.Copy_CR.txt_Search_CR.PressKeys(varCRNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Copy_CR.btn_Search_CR_Action' at Center.", repo.SimpleMDG.Copy_CR.btn_Search_CR_ActionInfo, new RecordItemIndex(6));
            repo.SimpleMDG.Copy_CR.btn_Search_CR_Action.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 28s to exist. Associated repository item: 'SimpleMDG.Copy_CR.lb_Requestor_Status_SUBMIT_Already'", repo.SimpleMDG.Copy_CR.lb_Requestor_Status_SUBMIT_AlreadyInfo, new ActionTimeout(28000), new RecordItemIndex(8));
            repo.SimpleMDG.Copy_CR.lb_Requestor_Status_SUBMIT_AlreadyInfo.WaitForExists(28000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'SimpleMDG.Copy_CR.btn_Menu_Option'", repo.SimpleMDG.Copy_CR.btn_Menu_OptionInfo, new ActionTimeout(10000), new RecordItemIndex(9));
            repo.SimpleMDG.Copy_CR.btn_Menu_OptionInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'SimpleMDG.Copy_CR.btn_Menu_Option'", repo.SimpleMDG.Copy_CR.btn_Menu_OptionInfo, new RecordItemIndex(10));
            repo.SimpleMDG.Copy_CR.btn_Menu_OptionInfo.WaitForAttributeEqual(5000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(11));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Copy_CR.btn_Menu_Option' at Center.", repo.SimpleMDG.Copy_CR.btn_Menu_OptionInfo, new RecordItemIndex(12));
            repo.SimpleMDG.Copy_CR.btn_Menu_Option.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Copy_CR.menu_Copy_Request' at Center.", repo.SimpleMDG.Copy_CR.menu_Copy_RequestInfo, new RecordItemIndex(13));
            repo.SimpleMDG.Copy_CR.menu_Copy_Request.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(14));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SimpleMDG.Input_Data.Product_Info.txt_Material_Number'", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo, new ActionTimeout(30000), new RecordItemIndex(15));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Product_Info.txt_Material_Number' at Center.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo, new RecordItemIndex(16));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_Number.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SimpleMDG.Input_Data.Product_Info.txt_Material_Number'.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo, new RecordItemIndex(17));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_Number.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varMaterial_Number' with focus on 'SimpleMDG.Input_Data.Product_Info.txt_Material_Number'.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo, new RecordItemIndex(18));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_Number.PressKeys(varMaterial_Number);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Product_Info.btn_Edit_Product_Description' at Center.", repo.SimpleMDG.Input_Data.Product_Info.btn_Edit_Product_DescriptionInfo, new RecordItemIndex(19));
            repo.SimpleMDG.Input_Data.Product_Info.btn_Edit_Product_Description.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Product_Info.txt_Material_description' at Center.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_descriptionInfo, new RecordItemIndex(20));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_description.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(21));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SimpleMDG.Input_Data.Product_Info.txt_Material_description'.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_descriptionInfo, new RecordItemIndex(22));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_description.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(23));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varMaterial_description' with focus on 'SimpleMDG.Input_Data.Product_Info.txt_Material_description'.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_descriptionInfo, new RecordItemIndex(24));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_description.PressKeys(varMaterial_description);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(25));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Product_Info.btn_Update_Product_Description' at Center.", repo.SimpleMDG.Input_Data.Product_Info.btn_Update_Product_DescriptionInfo, new RecordItemIndex(26));
            repo.SimpleMDG.Input_Data.Product_Info.btn_Update_Product_Description.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
