///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.SPMG_Action
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Copy_Request_byExist recording.
    /// </summary>
    [TestModule("634bafce-6d8a-4e61-9b35-3f7861f674b7", ModuleType.Recording, 1)]
    public partial class Copy_Request_byExist : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Copy_Request_byExist instance = new Copy_Request_byExist();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Copy_Request_byExist()
        {
            varCRNumber = "";
            varMaterial_Number = "";
            varMaterial_description = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Copy_Request_byExist Instance
        {
            get { return instance; }
        }

#region Variables

        string _varMaterial_description;

        /// <summary>
        /// Gets or sets the value of variable varMaterial_description.
        /// </summary>
        [TestVariable("b2c6da22-1a12-46ea-aa7c-e29368460a2e")]
        public string varMaterial_description
        {
            get { return _varMaterial_description; }
            set { _varMaterial_description = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varCRNumber.
        /// </summary>
        [TestVariable("ac241e23-ca02-4143-9eb1-224beaf00a1d")]
        public string varCRNumber
        {
            get { return repo.varCRNumber; }
            set { repo.varCRNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varMaterial_Number.
        /// </summary>
        [TestVariable("cd7be221-1d69-40e3-941b-008a16a6bd36")]
        public string varMaterial_Number
        {
            get { return repo.varMaterial_Number; }
            set { repo.varMaterial_Number = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(0));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'SimpleMDG.Copy_CR.txt_Search_CR'", repo.SimpleMDG.Copy_CR.txt_Search_CRInfo, new ActionTimeout(5000), new RecordItemIndex(1));
            repo.SimpleMDG.Copy_CR.txt_Search_CRInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Copy_CR.txt_Search_CR' at Center.", repo.SimpleMDG.Copy_CR.txt_Search_CRInfo, new RecordItemIndex(2));
            repo.SimpleMDG.Copy_CR.txt_Search_CR.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SimpleMDG.Copy_CR.txt_Search_CR'.", repo.SimpleMDG.Copy_CR.txt_Search_CRInfo, new RecordItemIndex(3));
            //repo.SimpleMDG.Copy_CR.txt_Search_CR.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(4));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'CR0000003848' with focus on 'SimpleMDG.Copy_CR.txt_Search_CR'.", repo.SimpleMDG.Copy_CR.txt_Search_CRInfo, new RecordItemIndex(5));
            repo.SimpleMDG.Copy_CR.txt_Search_CR.PressKeys("CR0000003848");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Copy_CR.btn_Search_CR_Action' at Center.", repo.SimpleMDG.Copy_CR.btn_Search_CR_ActionInfo, new RecordItemIndex(6));
            repo.SimpleMDG.Copy_CR.btn_Search_CR_Action.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SimpleMDG.Copy_CR.lb_Requestor_Status_SUBMIT_Already'", repo.SimpleMDG.Copy_CR.lb_Requestor_Status_SUBMIT_AlreadyInfo, new ActionTimeout(30000), new RecordItemIndex(8));
            repo.SimpleMDG.Copy_CR.lb_Requestor_Status_SUBMIT_AlreadyInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'SimpleMDG.Copy_CR.btn_Menu_Option'", repo.SimpleMDG.Copy_CR.btn_Menu_OptionInfo, new ActionTimeout(5000), new RecordItemIndex(9));
            repo.SimpleMDG.Copy_CR.btn_Menu_OptionInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(10));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Copy_CR.btn_Menu_Option' at Center.", repo.SimpleMDG.Copy_CR.btn_Menu_OptionInfo, new RecordItemIndex(11));
            repo.SimpleMDG.Copy_CR.btn_Menu_Option.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Copy_CR.menu_Copy_Request' at Center.", repo.SimpleMDG.Copy_CR.menu_Copy_RequestInfo, new RecordItemIndex(12));
            repo.SimpleMDG.Copy_CR.menu_Copy_Request.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(13));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'SimpleMDG.Input_Data.Product_Info.txt_Material_Number'", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo, new ActionTimeout(5000), new RecordItemIndex(14));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Product_Info.txt_Material_Number' at Center.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo, new RecordItemIndex(15));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_Number.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SimpleMDG.Input_Data.Product_Info.txt_Material_Number'.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo, new RecordItemIndex(16));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_Number.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varMaterial_Number' with focus on 'SimpleMDG.Input_Data.Product_Info.txt_Material_Number'.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo, new RecordItemIndex(17));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_Number.PressKeys(varMaterial_Number);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Product_Info.btn_Edit_Product_Description' at Center.", repo.SimpleMDG.Input_Data.Product_Info.btn_Edit_Product_DescriptionInfo, new RecordItemIndex(18));
            repo.SimpleMDG.Input_Data.Product_Info.btn_Edit_Product_Description.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Product_Info.txt_Material_description' at Center.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_descriptionInfo, new RecordItemIndex(19));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_description.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SimpleMDG.Input_Data.Product_Info.txt_Material_description'.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_descriptionInfo, new RecordItemIndex(20));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_description.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varMaterial_description' with focus on 'SimpleMDG.Input_Data.Product_Info.txt_Material_description'.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_descriptionInfo, new RecordItemIndex(21));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_description.PressKeys(varMaterial_description);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Product_Info.btn_Update_Product_Description' at Center.", repo.SimpleMDG.Input_Data.Product_Info.btn_Update_Product_DescriptionInfo, new RecordItemIndex(22));
            repo.SimpleMDG.Input_Data.Product_Info.btn_Update_Product_Description.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
