///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.SPMG_Action
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Copy_CR_From_Master_Data recording.
    /// </summary>
    [TestModule("6371aed5-b32b-4d00-a026-f2971ca03258", ModuleType.Recording, 1)]
    public partial class Copy_CR_From_Master_Data : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Copy_CR_From_Master_Data instance = new Copy_CR_From_Master_Data();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Copy_CR_From_Master_Data()
        {
            varMaterial_Number = "";
            varMaterial_description = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Copy_CR_From_Master_Data Instance
        {
            get { return instance; }
        }

#region Variables

        string _varMaterial_description;

        /// <summary>
        /// Gets or sets the value of variable varMaterial_description.
        /// </summary>
        [TestVariable("a71c841d-6048-44a3-b788-688070a56c2e")]
        public string varMaterial_description
        {
            get { return _varMaterial_description; }
            set { _varMaterial_description = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varMaterial_Number.
        /// </summary>
        [TestVariable("8429c1e4-57aa-4808-a842-ce3aa9c4a9d0")]
        public string varMaterial_Number
        {
            get { return repo.varMaterial_Number; }
            set { repo.varMaterial_Number = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(0));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SimpleMDG.Input_Data.Product_Info.txt_Material_Number'", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Product_Info.txt_Material_Number' at Center.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo, new RecordItemIndex(2));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_Number.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SimpleMDG.Input_Data.Product_Info.txt_Material_Number'.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo, new RecordItemIndex(3));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_Number.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varMaterial_Number' with focus on 'SimpleMDG.Input_Data.Product_Info.txt_Material_Number'.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_NumberInfo, new RecordItemIndex(4));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_Number.PressKeys(varMaterial_Number);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Product_Info.btn_Edit_Product_Description' at Center.", repo.SimpleMDG.Input_Data.Product_Info.btn_Edit_Product_DescriptionInfo, new RecordItemIndex(5));
            repo.SimpleMDG.Input_Data.Product_Info.btn_Edit_Product_Description.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Product_Info.txt_Material_description' at Center.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_descriptionInfo, new RecordItemIndex(6));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_description.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SimpleMDG.Input_Data.Product_Info.txt_Material_description'.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_descriptionInfo, new RecordItemIndex(8));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_description.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(9));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varMaterial_description' with focus on 'SimpleMDG.Input_Data.Product_Info.txt_Material_description'.", repo.SimpleMDG.Input_Data.Product_Info.txt_Material_descriptionInfo, new RecordItemIndex(10));
            repo.SimpleMDG.Input_Data.Product_Info.txt_Material_description.PressKeys(varMaterial_description);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(11));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Product_Info.btn_Update_Product_Description' at Center.", repo.SimpleMDG.Input_Data.Product_Info.btn_Update_Product_DescriptionInfo, new RecordItemIndex(12));
            repo.SimpleMDG.Input_Data.Product_Info.btn_Update_Product_Description.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
