///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.SPMG_Action
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Select_A_OT recording.
    /// </summary>
    [TestModule("651f9905-b999-430d-bfd1-e63519ff272f", ModuleType.Recording, 1)]
    public partial class Select_A_OT : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Select_A_OT instance = new Select_A_OT();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Select_A_OT()
        {
            varObjectType = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Select_A_OT Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varObjectType.
        /// </summary>
        [TestVariable("9680dbe4-b9cf-44d3-bc4f-5e5bfae96a8e")]
        public string varObjectType
        {
            get { return repo.varObjectType; }
            set { repo.varObjectType = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(0));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Choose_OT.btn_New_Request' at Center.", repo.SimpleMDG.Choose_OT.btn_New_RequestInfo, new RecordItemIndex(1));
            repo.SimpleMDG.Choose_OT.btn_New_Request.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Choose_OT.txt_Input_OT' at Center.", repo.SimpleMDG.Choose_OT.txt_Input_OTInfo, new RecordItemIndex(2));
            //repo.SimpleMDG.Choose_OT.txt_Input_OT.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varObjectType' with focus on 'SimpleMDG.Choose_OT.txt_Input_OT'.", repo.SimpleMDG.Choose_OT.txt_Input_OTInfo, new RecordItemIndex(3));
            repo.SimpleMDG.Choose_OT.txt_Input_OT.PressKeys(varObjectType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Choose_OT.btn_Next' at Center.", repo.SimpleMDG.Choose_OT.btn_NextInfo, new RecordItemIndex(4));
            repo.SimpleMDG.Choose_OT.btn_Next.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
