///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.SPMG_Action
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Select_Template recording.
    /// </summary>
    [TestModule("5152248a-4efa-4455-8cf5-4eeea5aafa11", ModuleType.Recording, 1)]
    public partial class Select_Template : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Select_Template instance = new Select_Template();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Select_Template()
        {
            varTemplate = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Select_Template Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varTemplate.
        /// </summary>
        [TestVariable("ccfc6f3c-0198-4af1-b06a-54f771b3c3db")]
        public string varTemplate
        {
            get { return repo.varTemplate; }
            set { repo.varTemplate = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'SimpleMDG.Select_Template.btn_SwitchTemplates'", repo.SimpleMDG.Select_Template.btn_SwitchTemplatesInfo, new ActionTimeout(5000), new RecordItemIndex(0));
            repo.SimpleMDG.Select_Template.btn_SwitchTemplatesInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Select_Template.btn_SwitchTemplates' at Center.", repo.SimpleMDG.Select_Template.btn_SwitchTemplatesInfo, new RecordItemIndex(2));
            repo.SimpleMDG.Select_Template.btn_SwitchTemplates.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Select_Template.txt_Search_Template' at Center.", repo.SimpleMDG.Select_Template.txt_Search_TemplateInfo, new RecordItemIndex(3));
            //repo.SimpleMDG.Select_Template.txt_Search_Template.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varTemplate' with focus on 'SimpleMDG.Select_Template.txt_Search_Template'.", repo.SimpleMDG.Select_Template.txt_Search_TemplateInfo, new RecordItemIndex(5));
            repo.SimpleMDG.Select_Template.txt_Search_Template.PressKeys(varTemplate);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Select_Template.btn_Search_Action' at Center.", repo.SimpleMDG.Select_Template.btn_Search_ActionInfo, new RecordItemIndex(6));
            repo.SimpleMDG.Select_Template.btn_Search_Action.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Select_Template.lb_Select_Template' at Center.", repo.SimpleMDG.Select_Template.lb_Select_TemplateInfo, new RecordItemIndex(7));
            repo.SimpleMDG.Select_Template.lb_Select_Template.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
