///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.SPMG_Action
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Submit_After_Update recording.
    /// </summary>
    [TestModule("662cbbd1-ef5a-4d38-9759-5e0e977117bb", ModuleType.Recording, 1)]
    public partial class Submit_After_Update : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Submit_After_Update instance = new Submit_After_Update();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Submit_After_Update()
        {
            varComment_Submit = "";
            CR_Number = "";
            CR_numberWithMessage = "";
            CR_Number_ORG = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Submit_After_Update Instance
        {
            get { return instance; }
        }

#region Variables

        string _varComment_Submit;

        /// <summary>
        /// Gets or sets the value of variable varComment_Submit.
        /// </summary>
        [TestVariable("901b0109-6aca-4f23-aaf2-a3d7c78504dd")]
        public string varComment_Submit
        {
            get { return _varComment_Submit; }
            set { _varComment_Submit = value; }
        }

        string _CR_Number;

        /// <summary>
        /// Gets or sets the value of variable CR_Number.
        /// </summary>
        [TestVariable("d9b08a93-cf21-4684-9e4a-3227024c28b7")]
        public string CR_Number
        {
            get { return _CR_Number; }
            set { _CR_Number = value; }
        }

        string _CR_numberWithMessage;

        /// <summary>
        /// Gets or sets the value of variable CR_numberWithMessage.
        /// </summary>
        [TestVariable("c5c5af16-ead8-4e85-bdc5-61fd6131430c")]
        public string CR_numberWithMessage
        {
            get { return _CR_numberWithMessage; }
            set { _CR_numberWithMessage = value; }
        }

        string _CR_Number_ORG;

        /// <summary>
        /// Gets or sets the value of variable CR_Number_ORG.
        /// </summary>
        [TestVariable("d7f4ba66-1243-409f-88cb-2dabe2496921")]
        public string CR_Number_ORG
        {
            get { return _CR_Number_ORG; }
            set { _CR_Number_ORG = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Submit_CR.btn_SubmitCR' at Center.", repo.SimpleMDG.Submit_CR.btn_SubmitCRInfo, new RecordItemIndex(0));
            repo.SimpleMDG.Submit_CR.btn_SubmitCR.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varComment_Submit' with focus on 'SimpleMDG.Submit_CR.txt_Comment_Submit'.", repo.SimpleMDG.Submit_CR.txt_Comment_SubmitInfo, new RecordItemIndex(1));
            repo.SimpleMDG.Submit_CR.txt_Comment_Submit.PressKeys(varComment_Submit);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Submit_CR.btn_Submit_Confirm' at Center.", repo.SimpleMDG.Submit_CR.btn_Submit_ConfirmInfo, new RecordItemIndex(2));
            repo.SimpleMDG.Submit_CR.btn_Submit_Confirm.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Get_CR_Number_Only(repo.SimpleMDG.Submit_CR.lb_CR_messageInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Submit_CR.btn_OK' at Center.", repo.SimpleMDG.Submit_CR.btn_OKInfo, new RecordItemIndex(5));
            repo.SimpleMDG.Submit_CR.btn_OK.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
