///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.SPMG_Action
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Submit_Validation_Duplication_Status_DUPLICATE recording.
    /// </summary>
    [TestModule("53db5865-0bcd-415c-9d8b-c1656f3f60b7", ModuleType.Recording, 1)]
    public partial class Submit_Validation_Duplication_Status_DUPLICATE : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Submit_Validation_Duplication_Status_DUPLICATE instance = new Submit_Validation_Duplication_Status_DUPLICATE();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Submit_Validation_Duplication_Status_DUPLICATE()
        {
            varComment_Submit = "";
            CR_Number = "";
            CR_numberWithMessage = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Submit_Validation_Duplication_Status_DUPLICATE Instance
        {
            get { return instance; }
        }

#region Variables

        string _varComment_Submit;

        /// <summary>
        /// Gets or sets the value of variable varComment_Submit.
        /// </summary>
        [TestVariable("5c9c03bd-407d-4178-855f-3d06181dfd4e")]
        public string varComment_Submit
        {
            get { return _varComment_Submit; }
            set { _varComment_Submit = value; }
        }

        string _CR_Number;

        /// <summary>
        /// Gets or sets the value of variable CR_Number.
        /// </summary>
        [TestVariable("4877d0a1-dc22-4fa5-afd2-97318cff12d2")]
        public string CR_Number
        {
            get { return _CR_Number; }
            set { _CR_Number = value; }
        }

        string _CR_numberWithMessage;

        /// <summary>
        /// Gets or sets the value of variable CR_numberWithMessage.
        /// </summary>
        [TestVariable("a5af299b-09e0-4008-b5b9-1849660f7898")]
        public string CR_numberWithMessage
        {
            get { return _CR_numberWithMessage; }
            set { _CR_numberWithMessage = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Submit_CR.btn_SubmitCR' at Center.", repo.SimpleMDG.Submit_CR.btn_SubmitCRInfo, new RecordItemIndex(0));
            repo.SimpleMDG.Submit_CR.btn_SubmitCR.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varComment_Submit' with focus on 'SimpleMDG.Submit_CR.txt_Comment_Submit'.", repo.SimpleMDG.Submit_CR.txt_Comment_SubmitInfo, new RecordItemIndex(1));
            repo.SimpleMDG.Submit_CR.txt_Comment_Submit.PressKeys(varComment_Submit);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Submit_CR.btn_Submit_Confirm' at Center.", repo.SimpleMDG.Submit_CR.btn_Submit_ConfirmInfo, new RecordItemIndex(2));
            repo.SimpleMDG.Submit_CR.btn_Submit_Confirm.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Get_value_lb_CR_message(repo.SimpleMDG.Submit_CR.lb_CR_messageInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Submit_CR.btn_OK' at Center.", repo.SimpleMDG.Submit_CR.btn_OKInfo, new RecordItemIndex(5));
            repo.SimpleMDG.Submit_CR.btn_OK.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'SimpleMDG.Copy_CR.txt_Search_CR'", repo.SimpleMDG.Copy_CR.txt_Search_CRInfo, new ActionTimeout(10000), new RecordItemIndex(7));
            repo.SimpleMDG.Copy_CR.txt_Search_CRInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Copy_CR.txt_Search_CR' at Center.", repo.SimpleMDG.Copy_CR.txt_Search_CRInfo, new RecordItemIndex(8));
            repo.SimpleMDG.Copy_CR.txt_Search_CR.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SimpleMDG.Copy_CR.txt_Search_CR'.", repo.SimpleMDG.Copy_CR.txt_Search_CRInfo, new RecordItemIndex(9));
            repo.SimpleMDG.Copy_CR.txt_Search_CR.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CR_Number' with focus on 'SimpleMDG.Copy_CR.txt_Search_CR'.", repo.SimpleMDG.Copy_CR.txt_Search_CRInfo, new RecordItemIndex(10));
            repo.SimpleMDG.Copy_CR.txt_Search_CR.PressKeys(CR_Number);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Copy_CR.btn_Search_CR_Action' at Center.", repo.SimpleMDG.Copy_CR.btn_Search_CR_ActionInfo, new RecordItemIndex(11));
            repo.SimpleMDG.Copy_CR.btn_Search_CR_Action.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(12));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'SimpleMDG.Copy_CR.btn_Requestor_Status_DUPLICATE'", repo.SimpleMDG.Copy_CR.btn_Requestor_Status_DUPLICATEInfo, new ActionTimeout(10000), new RecordItemIndex(13));
            repo.SimpleMDG.Copy_CR.btn_Requestor_Status_DUPLICATEInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='DUPLICATE') on item 'SimpleMDG.Copy_CR.btn_Requestor_Status_DUPLICATE'.", repo.SimpleMDG.Copy_CR.btn_Requestor_Status_DUPLICATEInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.SimpleMDG.Copy_CR.btn_Requestor_Status_DUPLICATEInfo, "InnerText", "DUPLICATE");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Copy_CR.btn_Requestor_Status_DUPLICATE' at Center.", repo.SimpleMDG.Copy_CR.btn_Requestor_Status_DUPLICATEInfo, new RecordItemIndex(15));
            repo.SimpleMDG.Copy_CR.btn_Requestor_Status_DUPLICATE.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Error Log') on item 'SimpleMDG.Validation_Status.lb_Error_Log'.", repo.SimpleMDG.Validation_Status.lb_Error_LogInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.SimpleMDG.Validation_Status.lb_Error_LogInfo, "InnerText", "Error Log");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (tagvalue>'Duplication found for below Product') on item 'SimpleMDG.Validation_Status.txt_Duplication_Error_Mgs'.", repo.SimpleMDG.Validation_Status.txt_Duplication_Error_MgsInfo, new RecordItemIndex(17));
            Validate.AttributeContains(repo.SimpleMDG.Validation_Status.txt_Duplication_Error_MgsInfo, "tagvalue", "Duplication found for below Product");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (tagvalue>'In Request') on item 'SimpleMDG.Validation_Status.txt_Duplication_Error_Mgs'.", repo.SimpleMDG.Validation_Status.txt_Duplication_Error_MgsInfo, new RecordItemIndex(18));
            Validate.AttributeContains(repo.SimpleMDG.Validation_Status.txt_Duplication_Error_MgsInfo, "tagvalue", "In Request");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (tagvalue>'Please check for below duplicate config') on item 'SimpleMDG.Validation_Status.txt_Duplication_Error_Mgs'.", repo.SimpleMDG.Validation_Status.txt_Duplication_Error_MgsInfo, new RecordItemIndex(19));
            Validate.AttributeContains(repo.SimpleMDG.Validation_Status.txt_Duplication_Error_MgsInfo, "tagvalue", "Please check for below duplicate config");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Validation_Status.btn_Close_Error_Mgs' at Center.", repo.SimpleMDG.Validation_Status.btn_Close_Error_MgsInfo, new RecordItemIndex(20));
            repo.SimpleMDG.Validation_Status.btn_Close_Error_Mgs.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
