///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.SPMG_Action
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SubnitCR recording.
    /// </summary>
    [TestModule("4cac7b3e-7461-4555-b490-81732f297977", ModuleType.Recording, 1)]
    public partial class SubnitCR : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static SubnitCR instance = new SubnitCR();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SubnitCR()
        {
            CR_numberWithMessage = "";
            CR_Number = "";
            CR_Number_ORG = "";
            varComment_Submit = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SubnitCR Instance
        {
            get { return instance; }
        }

#region Variables

        string _CR_numberWithMessage;

        /// <summary>
        /// Gets or sets the value of variable CR_numberWithMessage.
        /// </summary>
        [TestVariable("5de08039-eaa0-4a53-99a7-10a47ee9316c")]
        public string CR_numberWithMessage
        {
            get { return _CR_numberWithMessage; }
            set { _CR_numberWithMessage = value; }
        }

        string _CR_Number;

        /// <summary>
        /// Gets or sets the value of variable CR_Number.
        /// </summary>
        [TestVariable("375aecd8-fbdf-4ae6-b263-c53c431bf355")]
        public string CR_Number
        {
            get { return _CR_Number; }
            set { _CR_Number = value; }
        }

        string _CR_Number_ORG;

        /// <summary>
        /// Gets or sets the value of variable CR_Number_ORG.
        /// </summary>
        [TestVariable("58037841-360e-4315-921c-193ba911930a")]
        public string CR_Number_ORG
        {
            get { return _CR_Number_ORG; }
            set { _CR_Number_ORG = value; }
        }

        string _varComment_Submit;

        /// <summary>
        /// Gets or sets the value of variable varComment_Submit.
        /// </summary>
        [TestVariable("6a005947-9a20-464f-8e2e-9aeb79733302")]
        public string varComment_Submit
        {
            get { return _varComment_Submit; }
            set { _varComment_Submit = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Submit_CR.btn_SubmitCR' at Center.", repo.SimpleMDG.Submit_CR.btn_SubmitCRInfo, new RecordItemIndex(0));
            repo.SimpleMDG.Submit_CR.btn_SubmitCR.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varComment_Submit' with focus on 'SimpleMDG.Submit_CR.txt_Comment_Submit'.", repo.SimpleMDG.Submit_CR.txt_Comment_SubmitInfo, new RecordItemIndex(1));
            repo.SimpleMDG.Submit_CR.txt_Comment_Submit.PressKeys(varComment_Submit);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Submit_CR.btn_Submit_Confirm' at Center.", repo.SimpleMDG.Submit_CR.btn_Submit_ConfirmInfo, new RecordItemIndex(2));
            repo.SimpleMDG.Submit_CR.btn_Submit_Confirm.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Get_CR_Number_and_ORG(repo.SimpleMDG.Submit_CR.lb_CR_messageInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Submit_CR.btn_OK' at Center.", repo.SimpleMDG.Submit_CR.btn_OKInfo, new RecordItemIndex(5));
            repo.SimpleMDG.Submit_CR.btn_OK.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
