///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.Input_Data
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Add_Class recording.
    /// </summary>
    [TestModule("31b572be-5802-4fb7-a48c-7c80c2bd9173", ModuleType.Recording, 1)]
    public partial class Add_Class : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Add_Class instance = new Add_Class();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Add_Class()
        {
            varClass_Type = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Add_Class Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varClass_Type.
        /// </summary>
        [TestVariable("4464a3a9-0137-4144-8c26-2f7a20ded836")]
        public string varClass_Type
        {
            get { return repo.varClass_Type; }
            set { repo.varClass_Type = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Classification.btn_Add_Classification' at Center.", repo.SimpleMDG.Input_Data.Classification.btn_Add_ClassificationInfo, new RecordItemIndex(0));
            repo.SimpleMDG.Input_Data.Classification.btn_Add_Classification.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Classification.txt_Class_Type' at Center.", repo.SimpleMDG.Input_Data.Classification.txt_Class_TypeInfo, new RecordItemIndex(1));
            repo.SimpleMDG.Input_Data.Classification.txt_Class_Type.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Classification.txt_Search_Class_Type' at Center.", repo.SimpleMDG.Input_Data.Classification.txt_Search_Class_TypeInfo, new RecordItemIndex(2));
            //repo.SimpleMDG.Input_Data.Classification.txt_Search_Class_Type.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(3));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varClass_Type' with focus on 'SimpleMDG.Input_Data.Classification.txt_Search_Class_Type'.", repo.SimpleMDG.Input_Data.Classification.txt_Search_Class_TypeInfo, new RecordItemIndex(4));
            repo.SimpleMDG.Input_Data.Classification.txt_Search_Class_Type.PressKeys(varClass_Type);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Classification.btn_Search_Action' at Center.", repo.SimpleMDG.Input_Data.Classification.btn_Search_ActionInfo, new RecordItemIndex(5));
            repo.SimpleMDG.Input_Data.Classification.btn_Search_Action.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Classification.lb_Select_Class' at Center.", repo.SimpleMDG.Input_Data.Classification.lb_Select_ClassInfo, new RecordItemIndex(6));
            repo.SimpleMDG.Input_Data.Classification.lb_Select_Class.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Classification.btn_Add_Submit' at Center.", repo.SimpleMDG.Input_Data.Classification.btn_Add_SubmitInfo, new RecordItemIndex(7));
            repo.SimpleMDG.Input_Data.Classification.btn_Add_Submit.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
