///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.Input_Data
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The input_SALESORGDATA recording.
    /// </summary>
    [TestModule("96bfe933-0ce9-491c-a209-be1df4d13058", ModuleType.Recording, 1)]
    public partial class input_SALESORGDATA : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static input_SALESORGDATA instance = new input_SALESORGDATA();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public input_SALESORGDATA()
        {
            varSales_Organization = "";
            varProduct_Hierarchy_Sale = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static input_SALESORGDATA Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varSales_Organization.
        /// </summary>
        [TestVariable("f9a6311d-71ba-4e20-aa8f-3a6194db5532")]
        public string varSales_Organization
        {
            get { return repo.varSales_Organization; }
            set { repo.varSales_Organization = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varProduct_Hierarchy_Sale.
        /// </summary>
        [TestVariable("a89a07e1-9fd2-48cc-a861-03305ed35a0d")]
        public string varProduct_Hierarchy_Sale
        {
            get { return repo.varProduct_Hierarchy_Sale; }
            set { repo.varProduct_Hierarchy_Sale = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.SALES_ORG_DATA.menu_SALES_ORG_DATA' at Center.", repo.SimpleMDG.Input_Data.SALES_ORG_DATA.menu_SALES_ORG_DATAInfo, new RecordItemIndex(0));
            repo.SimpleMDG.Input_Data.SALES_ORG_DATA.menu_SALES_ORG_DATA.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.SALES_ORG_DATA.btn_Add_Sale_Org' at Center.", repo.SimpleMDG.Input_Data.SALES_ORG_DATA.btn_Add_Sale_OrgInfo, new RecordItemIndex(1));
            repo.SimpleMDG.Input_Data.SALES_ORG_DATA.btn_Add_Sale_Org.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.SALES_ORG_DATA.txt_Sales_Organization' at Center.", repo.SimpleMDG.Input_Data.SALES_ORG_DATA.txt_Sales_OrganizationInfo, new RecordItemIndex(2));
            repo.SimpleMDG.Input_Data.SALES_ORG_DATA.txt_Sales_Organization.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(3));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varSales_Organization' with focus on 'SimpleMDG.Input_Data.SALES_ORG_DATA.txt_Search_Sales_Org'.", repo.SimpleMDG.Input_Data.SALES_ORG_DATA.txt_Search_Sales_OrgInfo, new RecordItemIndex(4));
            repo.SimpleMDG.Input_Data.SALES_ORG_DATA.txt_Search_Sales_Org.PressKeys(varSales_Organization);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.SALES_ORG_DATA.btn_Search_Sales_Org_Action' at Center.", repo.SimpleMDG.Input_Data.SALES_ORG_DATA.btn_Search_Sales_Org_ActionInfo, new RecordItemIndex(5));
            repo.SimpleMDG.Input_Data.SALES_ORG_DATA.btn_Search_Sales_Org_Action.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.SALES_ORG_DATA.lb_Select_Sales_Org' at Center.", repo.SimpleMDG.Input_Data.SALES_ORG_DATA.lb_Select_Sales_OrgInfo, new RecordItemIndex(6));
            repo.SimpleMDG.Input_Data.SALES_ORG_DATA.lb_Select_Sales_Org.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.SALES_ORG_DATA.txt_Product_Hierarchy' at Center.", repo.SimpleMDG.Input_Data.SALES_ORG_DATA.txt_Product_HierarchyInfo, new RecordItemIndex(7));
            repo.SimpleMDG.Input_Data.SALES_ORG_DATA.txt_Product_Hierarchy.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(8));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varProduct_Hierarchy_Sale' with focus on 'SimpleMDG.Input_Data.SALES_ORG_DATA.txt_Search_Product_Hierarchy'.", repo.SimpleMDG.Input_Data.SALES_ORG_DATA.txt_Search_Product_HierarchyInfo, new RecordItemIndex(9));
            repo.SimpleMDG.Input_Data.SALES_ORG_DATA.txt_Search_Product_Hierarchy.PressKeys(varProduct_Hierarchy_Sale);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.SALES_ORG_DATA.btn_Search_Product_Hierarchy_Action' at Center.", repo.SimpleMDG.Input_Data.SALES_ORG_DATA.btn_Search_Product_Hierarchy_ActionInfo, new RecordItemIndex(10));
            repo.SimpleMDG.Input_Data.SALES_ORG_DATA.btn_Search_Product_Hierarchy_Action.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(11));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.SALES_ORG_DATA.lb_Select_Product_Hierarchy' at Center.", repo.SimpleMDG.Input_Data.SALES_ORG_DATA.lb_Select_Product_HierarchyInfo, new RecordItemIndex(12));
            repo.SimpleMDG.Input_Data.SALES_ORG_DATA.lb_Select_Product_Hierarchy.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.SALES_ORG_DATA.btn_Add_Sales_Org' at Center.", repo.SimpleMDG.Input_Data.SALES_ORG_DATA.btn_Add_Sales_OrgInfo, new RecordItemIndex(13));
            repo.SimpleMDG.Input_Data.SALES_ORG_DATA.btn_Add_Sales_Org.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
