///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.Input_Data
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Remove_Currency_Role recording.
    /// </summary>
    [TestModule("a8773bfc-c42b-4eef-81e9-6d7a91274607", ModuleType.Recording, 1)]
    public partial class Remove_Currency_Role : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Remove_Currency_Role instance = new Remove_Currency_Role();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Remove_Currency_Role()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Remove_Currency_Role Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.ACCOUNTING.mn_Accounting_and_Costing' at Center.", repo.SimpleMDG.ACCOUNTING.mn_Accounting_and_CostingInfo, new RecordItemIndex(0));
            repo.SimpleMDG.ACCOUNTING.mn_Accounting_and_Costing.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.ACCOUNTING.btn_Edit_Accounting' at Center.", repo.SimpleMDG.ACCOUNTING.btn_Edit_AccountingInfo, new RecordItemIndex(1));
            repo.SimpleMDG.ACCOUNTING.btn_Edit_Accounting.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(2));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.ACCOUNTING.txt_Currency_Role' at Center.", repo.SimpleMDG.ACCOUNTING.txt_Currency_RoleInfo, new RecordItemIndex(3));
            repo.SimpleMDG.ACCOUNTING.txt_Currency_Role.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(4));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Delete}' with focus on 'SimpleMDG.ACCOUNTING.txt_Currency_Role'.", repo.SimpleMDG.ACCOUNTING.txt_Currency_RoleInfo, new RecordItemIndex(5));
            repo.SimpleMDG.ACCOUNTING.txt_Currency_Role.PressKeys("{LControlKey down}{Akey}{LControlKey up}{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.ACCOUNTING.btn_Update_Accounting' at Center.", repo.SimpleMDG.ACCOUNTING.btn_Update_AccountingInfo, new RecordItemIndex(6));
            repo.SimpleMDG.ACCOUNTING.btn_Update_Accounting.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
