///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EDF__PRD_MM01.Input_Data
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Update_CLASSIFICATION recording.
    /// </summary>
    [TestModule("f1528183-f6cf-40e9-983c-67d88a3f0b95", ModuleType.Recording, 1)]
    public partial class Update_CLASSIFICATION : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repository.
        /// </summary>
        public static global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository repo = global::EDF__PRD_MM01.S2022_PRD_MM01_NON_DUPRepository.Instance;

        static Update_CLASSIFICATION instance = new Update_CLASSIFICATION();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Update_CLASSIFICATION()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Update_CLASSIFICATION Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Update_CLASSIFICATION.tab_Classification' at Center.", repo.SimpleMDG.Input_Data.Update_CLASSIFICATION.tab_ClassificationInfo, new RecordItemIndex(0));
            repo.SimpleMDG.Input_Data.Update_CLASSIFICATION.tab_Classification.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(1));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Update_CLASSIFICATION.ckb_Select_All_Class_Type' at Center.", repo.SimpleMDG.Input_Data.Update_CLASSIFICATION.ckb_Select_All_Class_TypeInfo, new RecordItemIndex(2));
            repo.SimpleMDG.Input_Data.Update_CLASSIFICATION.ckb_Select_All_Class_Type.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(3));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SimpleMDG.Input_Data.Update_CLASSIFICATION.btn_Remove_Class_Type' at Center.", repo.SimpleMDG.Input_Data.Update_CLASSIFICATION.btn_Remove_Class_TypeInfo, new RecordItemIndex(4));
            repo.SimpleMDG.Input_Data.Update_CLASSIFICATION.btn_Remove_Class_Type.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
